myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from allauth.account.views import LoginView, SignupView
from users import views as users_views
from courses import views as courses_views

admin.site.site_header = "Skilled MBA Administration"
admin.site.site_title = "Skilled MBA Administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", users_views.profile, name="account_profile"),
    path("ajax-login/", users_views.AjaxLoginView.as_view(), name="ajax_login"),
    path("ajax-signup/", users_views.AjaxSignupView.as_view(), name="ajax_signup"),
    path(
        "",
        courses_views.index,
        name="index",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="sitePages/contactUs.html"),
        name="contact_us",
    ),
    path("media-library/", include("media_library.urls", namespace="media_library")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("", include("users.urls", namespace="users")),
    path("quizzes/", include("quizzes.urls", namespace="quizzes")),
]

# For checking static files in developement only
urlpatterns += [
    path(
        "dashboard/analytics/",
        TemplateView.as_view(template_name="dashboard/instructor/analytics.html"),
        name="analytics",
    ),
    path(
        "dashboard/announcements/",
        TemplateView.as_view(template_name="dashboard/instructor/announcements.html"),
        name="announcements",
    ),
    path(
        "dashboard/quiz-attempts/",
        TemplateView.as_view(template_name="dashboard/instructor/quizAttempts.html"),
        name="quiz_attempts",
    ),
    path(
        "dashboard/withdrawals/",
        TemplateView.as_view(template_name="dashboard/instructor/withdrawals.html"),
        name="withdrawals",
    ),
    path(
        "course-list/",
        TemplateView.as_view(template_name="sitePages/courseList.html"),
        name="course_list",
    ),
    path(
        "course-assignment/",
        TemplateView.as_view(template_name="courseContents/assignment.html"),
        name="course_assignment",
    ),
    path(
        "course-lesson/",
        TemplateView.as_view(template_name="courseContents/lesson.html"),
        name="course_lesson",
    ),
    path(
        "course-quiz/",
        TemplateView.as_view(template_name="courseContents/quiz.html"),
        name="course_quiz",
    ),
    path(
        "enrolled-courses/",
        TemplateView.as_view(template_name="dashboard/student/enrolled_courses.html"),
        name="enrolled_courses",
    ),
    path(
        "reviews/",
        TemplateView.as_view(template_name="dashboard/student/reviews.html"),
        name="reviews",
    ),
    path(
        "wishlist/",
        TemplateView.as_view(template_name="dashboard/student/wishlist.html"),
        name="wishlist",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizzes/urls.py
from django.urls import path
from . import views

app_name = "quizzes"

urlpatterns = [
    path("mark-answer/<int:attempt_pk>/", views.mark_answer, name="mark_answer"),
    path("submit-answer/<int:attempt_pk>/", views.submit_answer, name="submit_answer"),
    path("quiz-attempts/", views.quiz_attempts, name="quiz_attempts"),
    path(
        "quiz-attempts/<int:pk>/", views.quiz_attempt_detail, name="quiz_attempt_detail"
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path(
        "accounts/become-instructor/", views.become_instructor, name="become_instructor"
    ),
    path(
        "instructor-registration/",
        views.InstructorSignupView.as_view(),
        name="instructor_signup",
    ),
    path(
        "search-instructors/<int:course_pk>/",
        views.search_instructors,
        name="search_instructors",
    ),
]

quizzes/models.py
from datetime import timedelta
import random
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from media_library.models import Media

User = get_user_model()

TIME_LIMIT_UNIT_CHOICES = (
    ("W", "Weeks"),
    ("D", "Days"),
    ("H", "Hours"),
    ("M", "Minutes"),
    ("S", "Seconds"),
)

FEEDBACK_MODE_CHOICES = (
    ("D", "Default"),  # Answers shown after quiz is finished
    ("R", "Reveal Mode"),  # Show result after the attempt.
    (
        "T",
        "Retry Mode",
    ),  # Reattempt quiz any number of times. Define Attempts Allowed below.
)

QUESTION_LAYOUT_CHOICES = (
    ("S", "Single Question"),
    ("B", "Question Below Each Other"),
)

QUESTION_ORDER_CHOICES = (
    ("R", "Random"),
    ("S", "Sorting"),
)

ANSWER_STATUS_CHOICES = (
    ("C", "Correct"),
    ("I", "Incorrect"),
    ("P", "Pending"),
)

QUESTION_TYPE_CHOICES = (
    ("TF", "True/False"),
    ("SC", "Single Choice"),
    ("MC", "Multiple Choice"),
    ("OE", "Open Ended"),
    ("FB", "Fill in the Blanks"),
    ("SA", "Short Answer"),
    ("M", "Matching"),
    ("IM", "Image Matching"),
    ("IA", "Image Answering"),
    ("O", "Ordering"),
)

DISPLAY_FORMAT_CHOICES = (
    ("T", "Only Text"),
    ("I", "Only Image"),
    ("B", "Text & Image both"),
)


def validate_max_duration(value):
    if value > timedelta(hours=1000):
        raise ValidationError("Maximum duration is 1000 hours.")


def validate_min_duration(value):
    if value < timedelta(seconds=0):
        raise ValidationError("Minimum duration is 0 second.")


class Quiz(models.Model):
    title = models.CharField(max_length=255)
    summary = models.TextField(blank=True)
    time_limit = models.DurationField(
        default=timedelta(),
        validators=[validate_max_duration, validate_min_duration],
        help_text="Time limit for this quiz. 0 means no time limit.",
    )
    time_limit_unit = models.CharField(
        max_length=1, choices=TIME_LIMIT_UNIT_CHOICES, default="W"
    )
    hide_time_display = models.BooleanField(default=False)
    feedback_mode = models.CharField(
        max_length=1, choices=FEEDBACK_MODE_CHOICES, default="D"
    )
    max_attempts_allowed = models.PositiveIntegerField(
        default=10,
        help_text="Restriction on the number of attempts a student is allowed to take for this quiz. 0 for no limit",
    )
    passing_percentage = models.FloatField(
        default=80, validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    max_questions = models.PositiveIntegerField(
        default=1,
        help_text="This amount of question will be available for students to answer, and question will comes randomly from all available questions belongs with a quiz, if this amount is greater than available question, then all questions will be available for a student to answer.",
        validators=[MinValueValidator(1)],
    )
    # Advance Settings
    auto_start = models.BooleanField(
        default=False,
        help_text="If you enable this option, the quiz will start automatically after the page is loaded.",
    )
    question_layout = models.CharField(
        max_length=1, choices=QUESTION_LAYOUT_CHOICES, default="S"
    )
    question_order = models.CharField(
        max_length=1, choices=QUESTION_ORDER_CHOICES, default="R"
    )
    hide_question_no = models.BooleanField(default=False)
    short_ans_char_limit = models.PositiveIntegerField(
        default=200,
        help_text="Student will place answer in short answer question type within this characters limit.",
    )
    long_ans_char_limit = models.PositiveIntegerField(
        default=500,
        help_text="Students will place the answer in the Open-Ended/Essay question type within this character limit.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(passing_percentage__gte=0.0)
                & models.Q(passing_percentage__lte=100.0),
                name="check_passing_percentage_range",
            ),
            models.CheckConstraint(
                check=models.Q(max_questions__gte=1), name="check_max_questions_range"
            ),
        ]
        ordering = ("-created_at",)
        verbose_name = "quiz"
        verbose_name_plural = "quizzes"

    def get_questions_count(self):
        return min(self.questions.count(), self.max_questions)

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions")
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    type = models.CharField(
        max_length=2,
        choices=QUESTION_TYPE_CHOICES,
        default="TF",
    )
    answer_required = models.BooleanField(default=False)
    randomize_options = models.BooleanField(default=False)
    points = models.FloatField(default=1)
    display_points = models.BooleanField(default=False)
    sort_order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # For True/False Question Type
    tf_correct_answer = models.BooleanField(default=True)
    tf_true_first = models.BooleanField(default=True)  # Show True first or False first
    # For Fill in the Blanks Question Type
    fb_question_title = models.CharField(
        max_length=255,
        blank=True,
        help_text="Please make sure to use the {dash} variable in your question title to show the blanks in your question. You can use multiple {dash} variables in one question.",
    )
    fb_correct_answer = models.CharField(
        max_length=255,
        blank=True,
        help_text="Separate multiple answers by a vertical bar |. 1 answer per {dash} variable is defined in the question. Example: Apple | Banana | Orange",
    )

    class Meta:
        ordering = ("quiz", "sort_order")

    def __str__(self):
        return self.title


class Option(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="options"
    )
    type = models.CharField(
        max_length=2,
        choices=QUESTION_TYPE_CHOICES,
        default="TF",
    )
    title = models.CharField(max_length=255)  # Used by SC, MC, IM, IA Question Types
    image = models.ForeignKey(
        Media,
        on_delete=models.CASCADE,
        related_name="image_for_options",
        null=True,
        blank=True,
    )
    display_format = models.CharField(
        max_length=1,
        choices=DISPLAY_FORMAT_CHOICES,
        default="T",
    )
    is_correct = models.BooleanField(default=False)
    sort_order = models.PositiveIntegerField(default=0)  # Also used by O Question Type
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # For Matching Question Type
    m_matched_ans_title = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ("question", "sort_order")

    def __str__(self):
        return self.title


class Attempt(models.Model):
    enrollment = models.ForeignKey(
        "courses.Enrollment", on_delete=models.CASCADE, related_name="quiz_attempts"
    )
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="attempts")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="quiz_attempts"
    )
    seed = models.PositiveIntegerField(default=0)
    is_completed = models.BooleanField(default=False)
    instructor_feedback = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    submitted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ("-submitted_at", "-created_at")

    def save(self, *args, **kwargs):
        if not self.pk:
            self.seed = random.randrange(10000)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.quiz.title} - {self.user.username}"


class Answer(models.Model):
    attempt = models.ForeignKey(
        Attempt, on_delete=models.CASCADE, related_name="answers"
    )
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers"
    )
    option = models.ForeignKey(
        Option,
        on_delete=models.CASCADE,
        related_name="answers",
        null=True,
        blank=True,
    )
    # For True/False Question Type
    tf_answer = models.BooleanField(default=True)
    # For FB, SA, OE, M, IM Question Type
    answer_text = models.TextField(blank=True)
    # For Ordering Question Type
    o_answer_order = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=1,
        choices=ANSWER_STATUS_CHOICES,
        default="P",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("attempt", "o_answer_order")

    def __str__(self):
        return f"{self.question.title} - {self.attempt.user.username}"

quizzes/views.py
import json
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Question, Option, Answer, Attempt


@require_POST
@login_required
def mark_answer(request, attempt_pk):
    attempt = get_object_or_404(Attempt, pk=attempt_pk, quiz__user=request.user)
    question_pk = request.POST.get("question_id")
    answers = attempt.answers.filter(attempt=attempt, question__pk=question_pk)
    status = request.POST.get("status")
    answers.update(status=status)
    return JsonResponse({"success": True})


@require_POST
@login_required
def submit_answer(request, attempt_pk):
    """
    Request Format:
    {
        "answers": [
            {
                "question_id": 1,
                "option_id": 1,
                "tf_answer": true,
                "answer_text": "Answer text",
                "o_answer_order": 1
            },
            ...
        ]
    }
    Errors on failure:
    {
        "error": [
            {
                "question": [
                    "This field is required."
                ]
            },
            null,
            ...
        ]
    }
    """
    attempt = get_object_or_404(Attempt, pk=attempt_pk, user=request.user)
    data = json.loads(request.body)
    answers = data.get("answers")
    answer_instances = []
    errors = []
    has_errors = False
    for answer in answers:
        question = Question.objects.get(pk=answer.get("question_id"))
        option = Option.objects.filter(pk=answer.get("option_id")).first()
        answer_instance = Answer(
            attempt=attempt,
            question=question,
            option=option,
            tf_answer=answer.get("tf_answer"),
            answer_text=answer.get("answer_text"),
            o_answer_order=answer.get("o_answer_order"),
        )

        # Validate the instance before saving
        try:
            answer_instance.full_clean()
            answer_instances.append(answer_instance)
            errors.append(None)
        except ValidationError as e:
            error = dict(e)
            errors.append(error)
            has_errors = True

    if has_errors:
        return JsonResponse({"error": errors}, status=400)

    question.answers.filter(attempt=attempt).delete()
    for answer_instance in answer_instances:
        answer_instance.save()

    return JsonResponse({"message": "Answer submitted successfully."})


# @login_required
# def fetch_answers(request, attempt_pk):
#     attempt = get_object_or_404(Attempt, pk=attempt_pk, user=request.user)
#     questions = attempt.quiz.questions.all()
#     answers = []
#     for question in questions:
#         answer = attempt.answers.filter(question=question).first()
#         if answer:
#             answers.append(answer)
#         else:
#             answers.append(None)
#     return JsonResponse({"answers": answers})


@login_required
def quiz_attempts(request):
    attempts = Attempt.objects.filter(
        quiz__topic_item__topic__course__user=request.user
    )
    return render(request, "quizzes/quiz_attempts.html", {"attempts": attempts})


@login_required
def quiz_attempt_detail(request, pk):
    attempt = get_object_or_404(
        Attempt, pk=pk, quiz__topic_item__topic__course__user=request.user
    )
    return render(request, "quizzes/quiz_attempt_detail.html", {"attempt": attempt})

quizzes/templates/quizzes/quiz_attempt_detail.html
{% extends "dashboard/base.html" %} {% block content %}
<script src="https://cdn.ckeditor.com/ckeditor5/39.0.0/classic/ckeditor.js"></script>
<!-- Page Content -->
<div>
    <!--Page Title-->
    <div class="container-fluid title-content">
        <div class="py-3" style="font-size: 14px">
            <div class="container mt-4">
                <p>
                    <a href="{% url 'quizzes:quiz_attempts' %}" class="text-primary"><i class="fas fa-long-arrow-left"></i> Back</a>
                </p>
                <p>Course: New Course</p>
                <h4>Demo Quiz</h4>
                <p>
                    Student: <b>Om Dahale</b>&nbsp;&nbsp;&nbsp;
                    Quiz Time: <b>0 Minutes</b>&nbsp;&nbsp;&nbsp;
                    Attempt Time: <b>16 Seconds</b>
                </p>
            </div>
        </div>
    </div>

    <!-- main Content -->
    <div class="container">
        <div class="card bg-transparent border-0 mb-5">
            <div class="card-body p-0 table-responsive border rounded">
                <table class="table m-0 align-middle">
                    <thead>
                        <tr>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Date</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Question</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Total&nbsp;Marks</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Pass&nbsp;Marks</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Correct&nbsp;Answer</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Incorrect&nbsp;Answer</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Earned&nbsp;Marks</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Result</b>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="p-4" style="font-size: 16px;">
                                <div class="fw-bold">August 8, 2023 7:40 am</div>
                            </td>
                            <td class="p-4 text-muted" style="font-size: 15px;">
                                <div class="fw-bold">1</div>
                            </td>
                            <td class="p-4 text-muted" style="font-size: 15px;">
                                <div class="fw-bold">1.0</div>
                            </td>
                            <td class="p-4 text-muted" style="font-size: 15px;">
                                <div class="fw-bold">0.80 (80%)</div>
                            </td>
                            <td class="p-4 text-muted" style="font-size: 15px;">
                                <div class="fw-bold">1</div>
                            </td>
                            <td class="p-4 text-muted" style="font-size: 15px;">
                                <div class="fw-bold">August 8, 2023 7:40 am</div>
                            </td>
                            <td class="p-4 text-muted" style="font-size: 15px;">
                                <div class="fw-bold"> 1.00 (100%)</div>
                            </td>
                            <td>
                                <div class="alert alert-danger py-1 px-2 mb-0 text-center"
                                    style="font-size: 12px; width: 80px;">
                                    Fail
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <h6>Quiz Overview</h6>
        <div class="card bg-transparent border-0 mb-5">
            <div class="card-body p-0 table-responsive border rounded">
                <table class="table m-0 align-middle">
                    <thead>

                        <tr>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>No</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Type</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Questions</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Given&nbsp;Answer</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Correct&nbsp;Answer</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Result</b>
                            </td>
                            <td scope="col" class="py-3 px-4 text-muted"
                                style="font-size: 15px; background: #f4f9ff;">
                                <b>Review</b>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="p-4" style="font-size: 16px;">
                                <div class="fw-bold">1</div>
                            </td>
                            <td class="p-4" style="font-size: 16px;">
                                <div class="fw-bold">type</div>
                            </td>
                            <td class="p-4" style="font-size: 16px;">
                                <div class="fw-bold">Question 66</div>
                            </td>
                            <td class="p-4" style="font-size: 16px;">
                                <div class="fw-bold">True</div>
                            </td>
                            <td class="p-4" style="font-size: 16px;">
                                <div class="fw-bold">False</div>
                            </td>
                            <td>
                                <div class="alert alert-danger py-1 px-2 mb-0 text-center"
                                    style="font-size: 12px; width: 80px;">
                                    Fail
                                </div>
                            </td>
                            <td class="p-4" style="font-size: 16px;">
                                <div class="d-flex gap-3">
                                    <button class="btn btn-outline-success">
                                        <i class="fas fa-check"></i>
                                    </button>
                                    <button class="btn btn-outline-danger">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <h6>Instructor Feedback</h6>
        <div id="instructorFeedback"></div>
        <button class="btn btn-primary p-3 my-4">
            Update
        </button>
    </div>
</div>

<script>
    ClassicEditor.create(document.querySelector("#instructorFeedback"));
</script>
{% endblock content %}

quizzes/templates/quizzes/quiz_attempts.html
{% extends "dashboard/base.html" %} {% block content %}
<div>
  <!--Page Title-->
  <div class="container-fluid title-content">
    <div class="py-3" style="font-size: 14px">
      <div class="container mt-4">
        <h3 class="fw-normal mb-3" style="letter-spacing: 1px">
          Quiz Attempts
        </h3>
      </div>
    </div>
  </div>

  <!-- Page Content -->
  <div class="container">
    <div class="card bg-transparent border-0">
      <div class="card-body p-0 table-responsive border rounded">
        <table class="table m-0 align-middle">
          <thead>
            <tr>
              <td scope="col" class="py-3 px-4 text-muted" style="font-size: 15px; background: #f4f9ff;">
                Course Info
              </td>
              <td scope="col" class="py-3 px-4 text-muted" style="font-size: 15px; background: #f4f9ff;">
                Student
              </td>
              <td scope="col" class="py-3 px-4 text-muted" style="font-size: 15px; background: #f4f9ff;">
                Correct&nbsp;Answers
              </td>
              <td scope="col" class="py-3 px-4 text-muted" style="font-size: 15px; background: #f4f9ff;">
                Incorrect&nbsp;Answers
              </td>
              <td scope="col" class="py-3 px-4 text-muted" style="font-size: 15px; background: #f4f9ff;">
                Earned&nbsp;Marks
              </td>
              <td colspan="2" class="py-3 px-4 text-muted" style="font-size: 15px; background: #f4f9ff;">
                Result
              </td>
            </tr>
          </thead>
          <tbody>
            {% for attempt in attempts %}
              <tr>
                <td class="p-4" style="font-size: 15px;">
                  <a href="#" style="font-weight: bolder">{{attempt.quiz.topic_item.topic.course.title}}</a><br />
                  <div class="d-flex gap-3 pt-2">
                      <small class="text-muted">{{attempt.created_at}}</small>
                      <small><span style="color: #9aa5b3;">Question:</span> <span style="font-weight: 300;">1</span></small>
                      <small><span style="color: #9aa5b3;">Total Marks:</span> <span style="font-weight: 300;">1.00</span><small>
                  </div>
                </td>
                <td class="p-4 text-muted" style="font-size: 15px;">
                  <small href="#">{{attempt.user.first_name}} {{attempt.user.last_name}}</small><br />
                  <small>{{attempt.user.email}}</small>
                </td>
                <td class="p-4" style="font-size: 15px;">1</td>
                <td class="p-4" style="font-size: 15px;">0</td>
                <td class="p-4" style="font-size: 15px;">1.00 (80%)</td>
                <td class="p-4" style="font-size: 15px;">
                  <div class="alert alert-danger py-1 px-2 mb-0 text-center" style="font-size: 12px; width: 80px;">Fail</div>
                </td>
                <td class="p-4" style="font-size: 15px;">
                  <a href="{% url 'quizzes:quiz_attempt_detail' attempt.pk %}" class="text-primary">Details</a>
                </td>
              </tr>
            {% endfor %}
            {% comment %} 
            <tr>
                <td class="p-4" style="font-size: 15px;">
                  <a href="#">Course Name</a><br />
                  <div class="d-flex gap-3 pt-2">
                      <div class="text-muted">August 8, 2023 7:40 am</div>
                      <div><span style="color: #9aa5b3;">Question:</span> <span style="font-weight: 300;">1</span></div>
                      <div><span style="color: #9aa5b3;">Total Marks:</span> <span style="font-weight: 300;">1.00</span><div>
                  </div>
                </td>
                <td class="p-4 text-muted" style="font-size: 15px;">
                  <a href="#">Student Name</a><br />
                  <small>Stud4nt Email</small>
                </td>
                <td class="p-4" style="font-size: 15px;">1</td>
                <td class="p-4" style="font-size: 15px;">0</td>
                <td class="p-4" style="font-size: 15px;">1.00 (80%)</td>
                <td class="p-4" style="font-size: 15px;">
                  <div class="alert alert-success py-1 px-2 mb-0 text-center" style="font-size: 12px; width: 80px;">Pass</div>
                </td>
                <td class="p-4" style="font-size: 15px;">
                  <a href="#" class="text-primary">Details</a>
                </td>
            </tr> 
            {% endcomment %}
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}