courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    # Main site
    path("", views.course_list, name="course_list"),
    path("<int:pk>/<str:slug>/", views.course_details, name="course_details"),
    path("enroll-course/<int:course_pk>/", views.enroll_course, name="enroll_course"),
    path("lessons/<int:pk>/", views.lesson_details, name="lesson_details"),
    path(
        "lessons/<int:pk>/mark-complete/",
        views.mark_lesson_complete,
        name="mark_lesson_complete",
    ),
    path("assignments/<int:pk>/", views.assignment_details, name="assignment_details"),
    path("quizzes/<int:pk>/", views.quiz_details, name="quiz_details"),
    # Dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("my-courses/", views.list_courses_published, name="list_courses_published"),
    path(
        "my-courses/pending-courses/",
        views.list_courses_pending,
        name="list_courses_pending",
    ),
    path(
        "my-courses/draft-courses/", views.list_courses_draft, name="list_courses_draft"
    ),
    path("create-course/", views.create_course, name="create_course"),
    path("update-course/<int:pk>/", views.update_course, name="update_course"),
    path("list-topics/<int:course_pk>/", views.list_topics, name="list_topics"),
    path("update-topic/<int:pk>/", views.update_topic, name="update_topic"),
    path("create-topic/<int:course_pk>/", views.create_topic, name="create_topic"),
    path("create-lesson/<int:topic_pk>/", views.create_lesson, name="create_lesson"),
    path("create-quiz/<int:topic_pk>/", views.create_quiz, name="create_quiz"),
    path(
        "create-question/<int:quiz_pk>/", views.create_question, name="create_question"
    ),
    path("create-option/<int:question_pk>/", views.create_option, name="create_option"),
    path(
        "create-assignment/<int:topic_pk>/",
        views.create_assignment,
        name="create_assignment",
    ),
    path("update-lesson/<int:pk>/", views.update_lesson, name="update_lesson"),
    path(
        "update-assignment/<int:pk>/", views.update_assignment, name="update_assignment"
    ),
    path("update-quiz/<int:pk>/", views.update_quiz, name="update_quiz"),
    path("update-question/<int:pk>/", views.update_question, name="update_question"),
    path("update-option/<int:pk>/", views.update_option, name="update_option"),
    path(
        "list-topic-item/<int:topic_pk>/",
        views.list_topic_items,
        name="list_topic_items",
    ),
    path(
        "list-questions/<int:quiz_pk>/",
        views.list_questions,
        name="list_questions",
    ),
    path(
        "list-options/<int:question_pk>/",
        views.list_options,
        name="list_options",
    ),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from allauth.account.views import LoginView, SignupView
from users import views as users_views
from courses import views as courses_views

admin.site.site_header = "Skilled MBA Administration"
admin.site.site_title = "Skilled MBA Administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", users_views.profile, name="account_profile"),
    path("ajax-login/", users_views.AjaxLoginView.as_view(), name="ajax_login"),
    path("ajax-signup/", users_views.AjaxSignupView.as_view(), name="ajax_signup"),
    path(
        "",
        courses_views.index,
        name="index",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="sitePages/contactUs.html"),
        name="contact_us",
    ),
    path("media-library/", include("media_library.urls", namespace="media_library")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("", include("users.urls", namespace="users")),
    path("quizzes/", include("quizzes.urls", namespace="quizzes")),
]

# For checking static files in developement only
urlpatterns += [
    path(
        "dashboard/analytics/",
        TemplateView.as_view(template_name="dashboard/instructor/analytics.html"),
        name="analytics",
    ),
    path(
        "dashboard/announcements/",
        TemplateView.as_view(template_name="dashboard/instructor/announcements.html"),
        name="announcements",
    ),
    path(
        "dashboard/quiz-attempts/",
        TemplateView.as_view(template_name="dashboard/instructor/quizAttempts.html"),
        name="quiz_attempts",
    ),
    path(
        "dashboard/withdrawals/",
        TemplateView.as_view(template_name="dashboard/instructor/withdrawals.html"),
        name="withdrawals",
    ),
    path(
        "course-list/",
        TemplateView.as_view(template_name="sitePages/courseList.html"),
        name="course_list",
    ),
    path(
        "course-assignment/",
        TemplateView.as_view(template_name="courseContents/assignment.html"),
        name="course_assignment",
    ),
    path(
        "course-lesson/",
        TemplateView.as_view(template_name="courseContents/lesson.html"),
        name="course_lesson",
    ),
    path(
        "course-quiz/",
        TemplateView.as_view(template_name="courseContents/quiz.html"),
        name="course_quiz",
    ),
    path(
        "enrolled-courses/",
        TemplateView.as_view(template_name="dashboard/student/enrolled_courses.html"),
        name="enrolled_courses",
    ),
    path(
        "reviews/",
        TemplateView.as_view(template_name="dashboard/student/reviews.html"),
        name="reviews",
    ),
    path(
        "wishlist/",
        TemplateView.as_view(template_name="dashboard/student/wishlist.html"),
        name="wishlist",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path(
        "accounts/become-instructor/", views.become_instructor, name="become_instructor"
    ),
    path(
        "instructor-registration/",
        views.InstructorSignupView.as_view(),
        name="instructor_signup",
    ),
    path(
        "search-instructors/<int:course_pk>/",
        views.search_instructors,
        name="search_instructors",
    ),
]

courses/models.py
from datetime import timedelta
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from media_library.models import Media
from quizzes.models import Quiz

User = get_user_model()

DIFFICULTY_LEVEL_CHOICES = (
    ("A", "All Levels"),
    ("B", "Beginner"),
    ("I", "Intermediate"),
    ("E", "Expert"),
)

LANGUAGE_CHOICES = (
    ("E", "English"),
    ("F", "French"),
    ("G", "German"),
    ("I", "Italian"),
    ("J", "Japanese"),
    ("K", "Korean"),
    ("R", "Russian"),
    ("S", "Spanish"),
)

TIME_LIMIT_UNIT_CHOICES = (
    ("W", "Weeks"),
    ("D", "Days"),
    ("H", "Hours"),
)


def validate_max_duration(value):
    if value > timedelta(hours=1000):
        raise ValidationError("Maximum duration is 1000 hours.")


def validate_min_duration(value):
    if value < timedelta(seconds=0):
        raise ValidationError("Minimum duration is 0 second.")


class CourseTag(models.Model):
    title = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ("title",)

    def __str__(self):
        return self.title


class CourseCategory(models.Model):
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="subcategories",
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ("title",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="courses")
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    max_students = models.PositiveIntegerField(
        default=0,
        help_text="Number of students that can enrol in this course. Set 0 for no limits.",
    )
    difficulty_level = models.CharField(
        max_length=1, choices=DIFFICULTY_LEVEL_CHOICES, default="A"
    )
    is_public = models.BooleanField(
        default=False, help_text="Make This Course Public. No enrollment required."
    )
    enable_qa = models.BooleanField(
        default=False, help_text="Enable Q&A section for your course"
    )
    language = models.CharField(max_length=1, choices=LANGUAGE_CHOICES, default="E")
    categories = models.ManyToManyField(
        CourseCategory, related_name="courses", blank=True
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True, default=0
    )
    discount_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True, default=0
    )
    thumbnail = models.ForeignKey(
        Media,
        on_delete=models.CASCADE,
        related_name="thumbnail_for_courses",
        null=True,
        blank=True,
    )
    instructors = models.ManyToManyField(
        User, related_name="courses_as_instructor", blank=True
    )
    attachments = models.ManyToManyField(
        Media, related_name="attachments_for_courses", blank=True
    )
    what_will_i_learn = models.TextField(
        blank=True, help_text="Write here the course benefits (One per line)"
    )
    target_audience = models.TextField(
        blank=True,
        help_text="Specify the target audience that will benefit the most from the course. (One line per target audience.)",
    )
    duration = models.DurationField(
        default=timedelta(),
        validators=[validate_max_duration, validate_min_duration],
    )
    materials_included = models.TextField(
        blank=True,
        help_text="A list of assets you will be providing for the students in this course (One per line)",
    )
    requirements = models.TextField(
        blank=True,
        help_text="Additional requirements or special instructions for the students (One per line)",
    )
    tags = models.ManyToManyField(CourseTag, related_name="courses", blank=True)
    prerequisite_courses = models.ManyToManyField(
        "self", symmetrical=False, related_name="prerequisite_for_courses", blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ("-created_at",)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_materials_included_lines(self):
        text = self.materials_included.replace("\r", "")
        return text.split("\n")

    def get_what_will_i_learn_lines(self):
        text = self.what_will_i_learn.replace("\r", "")
        return text.split("\n")

    def get_requirements_lines(self):
        text = self.requirements.replace("\r", "")
        return text.split("\n")

    def get_target_audience_lines(self):
        text = self.target_audience.replace("\r", "")
        return text.split("\n")

    def get_lessons_count(self):
        return Lesson.objects.filter(topic_item__topic__course=self).count()

    def get_percent_off(self):
        if self.price and self.discount_price:
            off = round((self.price - self.discount_price) / self.price * 100, 1)
            if off % 1 == 0:  # is integer for Decimal
                return int(off)
            return off

    def can_user_read(self, user):
        if self.user == user or user.is_superuser:
            return True
        is_course_instructor = self.instructors.filter(pk__in=[user.pk]).exists()
        if is_course_instructor:
            return True
        return self.approved_at != None

    def can_user_write(self, user):
        if self.user == user:
            return True
        is_course_instructor = self.instructors.filter(pk__in=[user.pk]).exists()
        if is_course_instructor:
            return True
        return False

    def __str__(self):
        return f"{self.user.username}'s course: {self.title}"


class Topic(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="topics")
    title = models.CharField(max_length=255)
    summary = models.TextField(blank=True)
    sort_order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("course", "sort_order")

    def __str__(self):
        return self.title


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    feature_image = models.ForeignKey(
        Media,
        on_delete=models.CASCADE,
        related_name="feature_image_for_topics",
        null=True,
        blank=True,
    )
    attachments = models.ManyToManyField(
        Media, related_name="attachments_for_lessons", blank=True
    )
    enable_preview = models.BooleanField(
        default=False,
        help_text="If checked, any users/guest can view this lesson without enroll course",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return self.title


class Assignment(models.Model):
    title = models.CharField(max_length=255)
    summary = models.TextField(blank=True)
    attachments = models.ManyToManyField(
        Media, related_name="attachments_for_assignments", blank=True
    )
    time_limit = models.DurationField(
        default=timedelta(),
        validators=[validate_max_duration, validate_min_duration],
    )
    time_limit_unit = models.CharField(
        max_length=1, choices=TIME_LIMIT_UNIT_CHOICES, default="W"
    )
    total_points = models.PositiveIntegerField(default=10)
    min_pass_points = models.PositiveIntegerField(default=5)
    max_file_uploads = models.PositiveIntegerField(
        default=1,
        help_text="Define the number of files that a student can upload in this assignment. Input 0 to disable the option to upload.",
    )
    file_size_limit = models.PositiveIntegerField(
        default=2, help_text="Define maximum file size attachment in MB"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def get_time_limit_display(self):
        if self.time_limit_unit == "W":
            return self.time_limit.days // 7
        elif self.time_limit_unit == "D":
            return self.time_limit.days
        elif self.time_limit_unit == "H":
            return self.time_limit.total_seconds() // 3600

    def __str__(self):
        return self.title


class TopicItem(models.Model):
    """
    This model is used to store the lesson, assignment, quiz for a topic and acts as a manager.
    """

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="items")
    sort_order = models.PositiveIntegerField(default=0)
    lesson = models.OneToOneField(
        Lesson,
        on_delete=models.CASCADE,
        related_name="topic_item",
        null=True,
        blank=True,
    )
    assignment = models.OneToOneField(
        Assignment,
        on_delete=models.CASCADE,
        related_name="topic_item",
        null=True,
        blank=True,
    )
    quiz = models.OneToOneField(
        Quiz,
        on_delete=models.CASCADE,
        related_name="topic_item",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("topic", "sort_order")

    def get_next_item(self):
        next_item = (
            self.topic.items.exclude(sort_order__lt=self.sort_order)
            .exclude(pk__in=[self.pk])
            .first()
        )
        if next_item is not None:

templates/courseContents/sidebar.html
<style>
    .activeSidebarTab {
        background-color: #eee;
    }
</style>
<div class="sidebar shadow-sm col-lg-4 p-0">
    <div class="d-flex">
        <div style="cursor: pointer;" class="sidebartab1 col-6 p-3 text-center">
            <i class="fal fa-book-open text-primary"></i>
            <small>
                <a class="text-muted" href="#">Lesson List</a>
            </small>
        </div>
        <div style="cursor: pointer;" class="sidebartab2 col-6 p-3 text-center">
            <i class="fal fa-question-circle text-primary"></i>
            <small>
                <a class="text-muted" href="#">Browse Q&A</a>
            </small>
        </div>
    </div>
    <div class="sidebartab1Content">
        {% with url_name=request.resolver_match.url_name %}
        <!--Topics card-->
        <div class="card text-start border-0">
            <div class="card-body p-0">
                {% for topic in course.topics.all %}
                <div class="section p-3 text-primary d-flex align-items-center justify-content-between gap-3"
                    style="cursor: pointer;" data-bs-toggle="collapse" href="#card{{forloop.counter}}">
                    <div class="d-flex align-items-center justify-content-between gap-3">
                        <small style="font-weight: 500;">{{topic.title}}</small>
                        <i class="fad fa-info-circle text-muted"></i>
                    </div>
                    {% if topic_item.topic == topic %}
                    <i class="fal fa-minus"></i>
                    {% else %}
                    <i class="fal fa-plus"></i>
                    {% endif %}
                </div>
                <div class="collapse {% if topic_item.topic == topic %}show{% endif %}" id="card{{forloop.counter}}">
                    <div class="mt-0">
                        <!--content in here-->
                        <table class="table table-striped m-0">
                            <tbody>
                                {% for ti in topic.items.all %}
                                <tr>
                                    <td class="{% if ti == topic_item %}bg-primary{% endif %}">
                                        {% if ti.lesson %}
                                        <a href="{% url 'courses:lesson_details' ti.lesson.pk %}"
                                            class="{% if ti == topic_item %}text-white{% else %}text-muted{% endif %}">
                                            <div class="py-2 px-4 d-flex justify-content-between align-items-center">
                                                <span><i
                                                        class="far fa-file-alt"></i>&nbsp;&nbsp;{{ti.lesson.title}}</span>
                                                <span>
                                                    {% if ti == topic_item %}
                                                    {% if ti.lesson in enrollment.completed_lessons.all %}
                                                    <i class="fas fa-check-circle text-light"></i>
                                                    {% else %}
                                                    <i class="far fa-circle text-light"></i>
                                                    {% endif %}
                                                    {% else %}
                                                    {% if ti.lesson in enrollment.completed_lessons.all %}
                                                    <i class="fas fa-check-circle text-success"></i>
                                                    {% else %}
                                                    <i class="far fa-circle" style="color: #a6a6a6;"></i>
                                                    {% endif %}
                                                    {% endif %}
                                                </span>
                                            </div>
                                        </a>
                                        {% elif ti.assignment %}
                                        <a href="{% url 'courses:assignment_details' ti.assignment.pk %}"
                                            class="{% if ti == topic_item %}text-white{% else %}text-muted{% endif %}">
                                            <div class="py-2 px-4 d-flex justify-content-between align-items-center">
                                                <span><i
                                                        class="far fa-file-edit"></i>&nbsp;&nbsp;{{ti.assignment.title}}</span>
                                                <span>
                                                    {% if ti == topic_item %}
                                                    <i class="far fa-circle text-light"></i>
                                                    {% else %}
                                                    <i class="far fa-circle" style="color: #a6a6a6;"></i>
                                                    {% endif %}
                                                </span>
                                            </div>
                                        </a>
                                        {% elif ti.quiz %}
                                        <a href="{% url 'courses:quiz_details' ti.quiz.pk %}"
                                            class="{% if ti == topic_item %}text-white{% else %}text-muted{% endif %}">
                                            <div class="py-2 px-4 d-flex justify-content-between align-items-center">
                                                <span><i class="far fa-question-circle"></i>&nbsp;&nbsp;Quiz</span>
                                                <span>
                                                    {% if ti == topic_item %}
                                                    <i class="far fa-circle text-light"></i>
                                                    {% else %}
                                                    <i class="far fa-circle" style="color: #a6a6a6;"></i>
                                                    {% endif %}
                                                </span>
                                            </div>
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endwith %}
    </div>
    <div class="sidebartab2Content">
        <div class="p-3">
            <div class="mb-5">
                <div class="d-flex align-items-center justify-content-between">
                    <h5>Q&A</h5>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#qaModal">
                        Ask a new question
                    </button>

                    <!-- Q&A Modal -->
                    <div class="modal fade" id="qaModal" tabindex="-1" aria-labelledby="qaModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="qaModalLabel">Ask a Question</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <textarea class="form-control" name="question" cols="30" rows="10"></textarea>
                                </div>
                                <div class="modal-footer d-flex gap-4 justify-content-center">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Cancel</button>
                                    <button type="button" class="btn btn-primary">Post Question</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="my-4">
                    <!--Question 1-->
                    <div class="d-flex align-items-cente gap-3">
                        <div style="width: 50px; height: 50px; font-size: 25px; background: #f1f3f8;"
                            class="rounded-circle d-flex align-items-center justify-content-center text-primary">
                            <img src="https://placehold.co/35x35" alt="testi" style="width: 100%;"
                                class="img-fluid rounded-circle">
                        </div>
                        <div class="d-flex flex-column gap-3" style="font-size: 14px; width: 100%;">
                            <div>
                                <b>Om Dahale</b>
                                <span class="text-muted">36 seconds ago</span>
                            </div>
                            <div class="p-3 rounded" style="background: #f8f8f8;">
                                how to do this?
                            </div>
                            <!--Answer 1-->
                            <div class="d-flex align-items-cente gap-3">
                                <div style="width: 50px; height: 50px; font-size: 25px; background: #f1f3f8;"
                                    class="rounded-circle d-flex align-items-center justify-content-center text-primary">
                                    <img src="https://placehold.co/35x35" alt="testi" style="width: 100%;"
                                        class="img-fluid rounded-circle">
                                </div>
                                <div class="d-flex flex-column gap-3" style="font-size: 14px; width: 100%;">
                                    <div>
                                        <b>Om Dahale</b>
                                        <span class="text-muted">36 seconds ago</span>
                                    </div>
                                    <div class="p-3 rounded" style="background: #f8f8f8;">
                                        how to do what?
                                    </div>
                                </div>
                            </div>
                            <!--Answer 2-->
                            <div class="d-flex align-items-cente gap-3">
                                <div style="width: 50px; height: 50px; font-size: 25px; background: #f1f3f8;"
                                    class="rounded-circle d-flex align-items-center justify-content-center text-primary">
                                    <img src="https://placehold.co/35x35" alt="testi" style="width: 100%;"
                                        class="img-fluid rounded-circle">
                                </div>
                                <div class="d-flex flex-column gap-3" style="font-size: 14px; width: 100%;">
                                    <div>
                                        <b>Om Dahale</b>
                                        <span class="text-muted">36 seconds ago</span>
                                    </div>
                                    <div class="p-3 rounded" style="background: #f8f8f8;">
                                        i don't know, ask the expert
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex justify-content-end mt-4">
                                <button class="btn btn-warning">Add an answer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(".sidebartab2Content").hide();
        $(".sidebartab2").addClass("activeSidebarTab");

        $(".sidebartab2").click(function () {
            $(".sidebartab1Content").hide();
            $(".sidebartab2Content").show();
            $(".sidebartab2").removeClass("activeSidebarTab");
            $(".sidebartab1").addClass("activeSidebarTab");
        });

        $(".sidebartab1").click(function () {
            $(".sidebartab2Content").hide();
            $(".sidebartab1Content").show();
            $(".sidebartab1").removeClass("activeSidebarTab");
            $(".sidebartab2").addClass("activeSidebarTab");
        });
    });
</script>