courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    # Main site
    path("", views.course_list, name="course_list"),
    path("<int:pk>/<str:slug>/", views.course_details, name="course_details"),
    path("enroll-course/<int:course_pk>/", views.enroll_course, name="enroll_course"),
    path("lessons/<int:pk>/", views.lesson_details, name="lesson_details"),
    path(
        "lessons/<int:pk>/mark-complete/",
        views.mark_lesson_complete,
        name="mark_lesson_complete",
    ),
    path("assignments/<int:pk>/", views.assignment_details, name="assignment_details"),
    path("quizzes/<int:pk>/", views.quiz_details, name="quiz_details"),
    # Dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("my-courses/", views.list_courses_published, name="list_courses_published"),
    path(
        "my-courses/pending-courses/",
        views.list_courses_pending,
        name="list_courses_pending",
    ),
    path(
        "my-courses/draft-courses/", views.list_courses_draft, name="list_courses_draft"
    ),
    path("create-course/", views.create_course, name="create_course"),
    path("update-course/<int:pk>/", views.update_course, name="update_course"),
    path("list-topics/<int:course_pk>/", views.list_topics, name="list_topics"),
    path("update-topic/<int:pk>/", views.update_topic, name="update_topic"),
    path("create-topic/<int:course_pk>/", views.create_topic, name="create_topic"),
    path("create-lesson/<int:topic_pk>/", views.create_lesson, name="create_lesson"),
    path("create-quiz/<int:topic_pk>/", views.create_quiz, name="create_quiz"),
    path(
        "create-question/<int:quiz_pk>/", views.create_question, name="create_question"
    ),
    path("create-option/<int:question_pk>/", views.create_option, name="create_option"),
    path(
        "create-assignment/<int:topic_pk>/",
        views.create_assignment,
        name="create_assignment",
    ),
    path("update-lesson/<int:pk>/", views.update_lesson, name="update_lesson"),
    path(
        "update-assignment/<int:pk>/", views.update_assignment, name="update_assignment"
    ),
    path("update-quiz/<int:pk>/", views.update_quiz, name="update_quiz"),
    path("update-question/<int:pk>/", views.update_question, name="update_question"),
    path("update-option/<int:pk>/", views.update_option, name="update_option"),
    path(
        "list-topic-item/<int:topic_pk>/",
        views.list_topic_items,
        name="list_topic_items",
    ),
    path(
        "list-questions/<int:quiz_pk>/",
        views.list_questions,
        name="list_questions",
    ),
    path(
        "list-options/<int:question_pk>/",
        views.list_options,
        name="list_options",
    ),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from allauth.account.views import LoginView, SignupView
from users import views as users_views
from courses import views as courses_views

admin.site.site_header = "Skilled MBA Administration"
admin.site.site_title = "Skilled MBA Administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", users_views.profile, name="account_profile"),
    path("ajax-login/", users_views.AjaxLoginView.as_view(), name="ajax_login"),
    path("ajax-signup/", users_views.AjaxSignupView.as_view(), name="ajax_signup"),
    path(
        "",
        courses_views.index,
        name="index",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="sitePages/contactUs.html"),
        name="contact_us",
    ),
    path("media-library/", include("media_library.urls", namespace="media_library")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("", include("users.urls", namespace="users")),
    path("quizzes/", include("quizzes.urls", namespace="quizzes")),
]

# For checking static files in developement only
urlpatterns += [
    path(
        "dashboard/analytics/",
        TemplateView.as_view(template_name="dashboard/instructor/analytics.html"),
        name="analytics",
    ),
    path(
        "dashboard/announcements/",
        TemplateView.as_view(template_name="dashboard/instructor/announcements.html"),
        name="announcements",
    ),
    path(
        "dashboard/quiz-attempts/",
        TemplateView.as_view(template_name="dashboard/instructor/quizAttempts.html"),
        name="quiz_attempts",
    ),
    path(
        "dashboard/withdrawals/",
        TemplateView.as_view(template_name="dashboard/instructor/withdrawals.html"),
        name="withdrawals",
    ),
    path(
        "course-list/",
        TemplateView.as_view(template_name="sitePages/courseList.html"),
        name="course_list",
    ),
    path(
        "course-assignment/",
        TemplateView.as_view(template_name="courseContents/assignment.html"),
        name="course_assignment",
    ),
    path(
        "course-lesson/",
        TemplateView.as_view(template_name="courseContents/lesson.html"),
        name="course_lesson",
    ),
    path(
        "course-quiz/",
        TemplateView.as_view(template_name="courseContents/quiz.html"),
        name="course_quiz",
    ),
    path(
        "enrolled-courses/",
        TemplateView.as_view(template_name="dashboard/student/enrolled_courses.html"),
        name="enrolled_courses",
    ),
    path(
        "reviews/",
        TemplateView.as_view(template_name="dashboard/student/reviews.html"),
        name="reviews",
    ),
    path(
        "wishlist/",
        TemplateView.as_view(template_name="dashboard/student/wishlist.html"),
        name="wishlist",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path(
        "accounts/become-instructor/", views.become_instructor, name="become_instructor"
    ),
    path(
        "instructor-registration/",
        views.InstructorSignupView.as_view(),
        name="instructor_signup",
    ),
    path(
        "search-instructors/<int:course_pk>/",
        views.search_instructors,
        name="search_instructors",
    ),
]

courses/models.py
from datetime import timedelta
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from media_library.models import Media
from quizzes.models import Quiz

User = get_user_model()

DIFFICULTY_LEVEL_CHOICES = (
    ("A", "All Levels"),
    ("B", "Beginner"),
    ("I", "Intermediate"),
    ("E", "Expert"),
)

LANGUAGE_CHOICES = (
    ("E", "English"),
    ("F", "French"),
    ("G", "German"),
    ("I", "Italian"),
    ("J", "Japanese"),
    ("K", "Korean"),
    ("R", "Russian"),
    ("S", "Spanish"),
)

TIME_LIMIT_UNIT_CHOICES = (
    ("W", "Weeks"),
    ("D", "Days"),
    ("H", "Hours"),
)


def validate_max_duration(value):
    if value > timedelta(hours=1000):
        raise ValidationError("Maximum duration is 1000 hours.")


def validate_min_duration(value):
    if value < timedelta(seconds=0):
        raise ValidationError("Minimum duration is 0 second.")


class CourseTag(models.Model):
    title = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ("title",)

    def __str__(self):
        return self.title


class CourseCategory(models.Model):
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="subcategories",
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ("title",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="courses")
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    max_students = models.PositiveIntegerField(
        default=0,
        help_text="Number of students that can enrol in this course. Set 0 for no limits.",
    )
    difficulty_level = models.CharField(
        max_length=1, choices=DIFFICULTY_LEVEL_CHOICES, default="A"
    )
    is_public = models.BooleanField(
        default=False, help_text="Make This Course Public. No enrollment required."
    )
    enable_qa = models.BooleanField(
        default=False, help_text="Enable Q&A section for your course"
    )
    language = models.CharField(max_length=1, choices=LANGUAGE_CHOICES, default="E")
    categories = models.ManyToManyField(
        CourseCategory, related_name="courses", blank=True
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True, default=0
    )
    discount_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True, default=0
    )
    thumbnail = models.ForeignKey(
        Media,
        on_delete=models.CASCADE,
        related_name="thumbnail_for_courses",
        null=True,
        blank=True,
    )
    instructors = models.ManyToManyField(
        User, related_name="courses_as_instructor", blank=True
    )
    attachments = models.ManyToManyField(
        Media, related_name="attachments_for_courses", blank=True
    )
    what_will_i_learn = models.TextField(
        blank=True, help_text="Write here the course benefits (One per line)"
    )
    target_audience = models.TextField(
        blank=True,
        help_text="Specify the target audience that will benefit the most from the course. (One line per target audience.)",
    )
    duration = models.DurationField(
        default=timedelta(),
        validators=[validate_max_duration, validate_min_duration],
    )
    materials_included = models.TextField(
        blank=True,
        help_text="A list of assets you will be providing for the students in this course (One per line)",
    )
    requirements = models.TextField(
        blank=True,
        help_text="Additional requirements or special instructions for the students (One per line)",
    )
    tags = models.ManyToManyField(CourseTag, related_name="courses", blank=True)
    prerequisite_courses = models.ManyToManyField(
        "self", symmetrical=False, related_name="prerequisite_for_courses", blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ("-created_at",)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_materials_included_lines(self):
        text = self.materials_included.replace("\r", "")
        return text.split("\n")

    def get_what_will_i_learn_lines(self):
        text = self.what_will_i_learn.replace("\r", "")
        return text.split("\n")

    def get_requirements_lines(self):
        text = self.requirements.replace("\r", "")
        return text.split("\n")

    def get_target_audience_lines(self):
        text = self.target_audience.replace("\r", "")
        return text.split("\n")

    def get_lessons_count(self):
        return Lesson.objects.filter(topic_item__topic__course=self).count()

    def get_percent_off(self):
        if self.price and self.discount_price:
            off = round((self.price - self.discount_price) / self.price * 100, 1)
            if off % 1 == 0:  # is integer for Decimal
                return int(off)
            return off

    def can_user_read(self, user):
        if self.user == user or user.is_superuser:
            return True
        is_course_instructor = self.instructors.filter(pk__in=[user.pk]).exists()
        if is_course_instructor:
            return True
        return self.approved_at != None

    def can_user_write(self, user):
        if self.user == user:
            return True
        is_course_instructor = self.instructors.filter(pk__in=[user.pk]).exists()
        if is_course_instructor:
            return True
        return False

    def __str__(self):
        return f"{self.user.username}'s course: {self.title}"


class Topic(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="topics")
    title = models.CharField(max_length=255)
    summary = models.TextField(blank=True)
    sort_order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("course", "sort_order")

    def __str__(self):
        return self.title


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    feature_image = models.ForeignKey(
        Media,
        on_delete=models.CASCADE,
        related_name="feature_image_for_topics",
        null=True,
        blank=True,
    )
    attachments = models.ManyToManyField(
        Media, related_name="attachments_for_lessons", blank=True
    )
    enable_preview = models.BooleanField(
        default=False,
        help_text="If checked, any users/guest can view this lesson without enroll course",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return self.title


class Assignment(models.Model):
    title = models.CharField(max_length=255)
    summary = models.TextField(blank=True)
    attachments = models.ManyToManyField(
        Media, related_name="attachments_for_assignments", blank=True
    )
    time_limit = models.DurationField(
        default=timedelta(),
        validators=[validate_max_duration, validate_min_duration],
    )
    time_limit_unit = models.CharField(
        max_length=1, choices=TIME_LIMIT_UNIT_CHOICES, default="W"
    )
    total_points = models.PositiveIntegerField(default=10)
    min_pass_points = models.PositiveIntegerField(default=5)
    max_file_uploads = models.PositiveIntegerField(
        default=1,
        help_text="Define the number of files that a student can upload in this assignment. Input 0 to disable the option to upload.",
    )
    file_size_limit = models.PositiveIntegerField(
        default=2, help_text="Define maximum file size attachment in MB"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def get_time_limit_display(self):
        if self.time_limit_unit == "W":
            return self.time_limit.days // 7
        elif self.time_limit_unit == "D":
            return self.time_limit.days
        elif self.time_limit_unit == "H":
            return self.time_limit.total_seconds() // 3600

    def __str__(self):
        return self.title


class TopicItem(models.Model):
    """
    This model is used to store the lesson, assignment, quiz for a topic and acts as a manager.
    """

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="items")
    sort_order = models.PositiveIntegerField(default=0)
    lesson = models.OneToOneField(
        Lesson,
        on_delete=models.CASCADE,
        related_name="topic_item",
        null=True,
        blank=True,
    )
    assignment = models.OneToOneField(
        Assignment,
        on_delete=models.CASCADE,
        related_name="topic_item",
        null=True,
        blank=True,
    )
    quiz = models.OneToOneField(
        Quiz,
        on_delete=models.CASCADE,
        related_name="topic_item",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("topic", "sort_order")

    def get_next_item(self):
        next_item = (
            self.topic.items.exclude(sort_order__lt=self.sort_order)
            .exclude(pk__in=[self.pk])
            .first()
        )
        if next_item is not None:

courses/forms.py
# forms.py

from django import forms
from .models import Course


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = (
            "title",
            "slug",
            "description",
            "max_students",
            "difficulty_level",
            "is_public",
            "enable_qa",
            "language",
            "categories",
            "price",
            "discount_price",
            "thumbnail",
            "instructors",
            "attachments",
            "what_will_i_learn",
            "target_audience",
            "duration",
            "materials_included",
            "requirements",
            "tags",
            "prerequisite_courses",
        )

    # def __init__(self, *args, **kwargs):
    #     super(ProductForm, self).__init__(*args, **kwargs)

    #     # Customize the field widgets or querysets if needed
    #     self.fields["category"].widget.attrs.update({"class": "custom-select"})
    #     self.fields["tags"].widget.attrs.update({"class": "custom-select"})

    #     # Optionally, you can limit the choices for the category field or tags field
    #     self.fields["category"].queryset = Category.objects.all()
    #     self.fields["tags"].queryset = Tag.objects.all()

courses/templates/courses/courseAttachments.html
<div class="card text-start mb-3">
    <div class="card-body p-0">
        <div class="section p-4" style="cursor: pointer;" data-bs-toggle="collapse" href="#card5">
            <i class="fas fa-chevron-down text-primary"></i>
            <span class="fs-4">&nbsp;&nbsp;Course Attachments</span>
        </div>
        <div class="collapse show" id="card5">
            <div class="m-4 mt-0">
                <!--content in here-->
                <button class="btn btn-outline-primary p-3">
                    <i class="fal fa-paperclip"></i>
                    <span>&nbsp;&nbsp;Upload Attachments</span>
                </button>
            </div>
        </div>
    </div>
</div>

courses/templates/courses/courseBuilder.html
{% load static %}
<!--Course Builder-->
<div class="card text-start mb-3">
  <div class="card-body p-0">
    <div class="section p-4" style="cursor: pointer" data-bs-toggle="collapse" href="#card3">
      <i class="fas fa-chevron-down text-primary"></i>
      <span class="fs-4">&nbsp;&nbsp;Course Builder</span>
    </div>
    <div class="collapse show" id="card3">
      <div class="m-4 mt-0">
        <div class="row">
          <div id="topic-list">
            <div id="topicsList"></div>
          </div>
        </div>
        <button type="button" class="btn btn-primary p-3" data-bs-toggle="modal" data-bs-target="#topicModal">
          <i class="fas fa-plus-square"></i>
          <span>&nbsp;&nbsp;Add New Topic</span>
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    fetchTopicsList();
    // Create Topic
    $("#topic-create-form").submit(function (e) {
      e.preventDefault();
      const form = $(this);
      const url = "{% url 'courses:create_topic' course.pk %}";

      $.ajax({
        type: "POST",
        url: url,
        data: new FormData(this),
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
        },
        processData: false,
        contentType: false,
        success: function (response) {
          // alert(response.message);
          // Refresh media list after successful upload
          fetchTopicsList();
          form.trigger("reset");
          $("#topicModal").modal("hide");
        },
        error: function (xhr, status, error) {
          alert("Error: " + xhr.responseJSON.error);
          // Handle the error and update the UI accordingly
        },
      });
    });

    // Update Topic form
    $("#updateTopicForm").submit(function (event) {
      event.preventDefault();

      $("#saveUpdateTopic").html(
        '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> <b>Saving...</b>'
      );

      topicId = $("#updateTopicForm input[name='topicId']").val();
      url = `/courses/update-topic/${topicId}/`;
      form = $("#updateTopicForm").serialize();

      $.ajax({
        type: "POST",
        url: url,
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
        },
        data: form,
        success: function (data) {
          $("#saveUpdateTopic").html("<span><b>Save Topic</b></span>");
          $("#updateTopicModal").modal("hide");
          fetchTopicsList();
        },
        error: function (xhr, status, error) {
          var errorMessage = JSON.parse(xhr.responseText).error_message;
          console.log(errorMessage);
        },
      });
    });

    

    const updateTopicModal = document.getElementById("updateTopicModal");
    if (updateTopicModal) {
      updateTopicModal.addEventListener("show.bs.modal", (event) => {
        const button = event.relatedTarget;
        const topicId = button.getAttribute("data-bs-topic-id");
        const topicTitle = button.getAttribute("data-bs-topic-title");
        const topicSummary = button.getAttribute("data-bs-topic-summary");
        const topicSortOrder = button.getAttribute("data-bs-topic-sort");

        const modalTitle = updateTopicModal.querySelector(".modal-title");
        modalTitle.textContent = `Edit: ${topicTitle}`;

        $("#updateTopicForm input[name='title']").val(topicTitle);
        $("#updateTopicForm input[name='topicId']").val(topicId);
        $("#updateTopicForm textarea[name='summary']").val(topicSummary);
        $("#updateTopicForm input[name='sort_order']").val(topicSortOrder);
      });
    }

    // Sortable Topic list
    const sortableTopicList = new Sortable(
      document.getElementById("topicsList"),
      {
        handle: '.SortHandle',
        animation: 150,
        onEnd: function (evt) {
          const item = evt.item;
          console.log("item", item)
          const newIndex = evt.newIndex;
          console.log("index", newIndex)
          const topicId = $(item)
            .find(".editTopicButton")
            .attr("data-bs-topic-id");
          const topicTitle = $(item)
            .find(".editTopicButton")
            .attr("data-bs-topic-title");
          const topicSummary = $(item)
            .find(".editTopicButton")
            .attr("data-bs-topic-summary");

          url = `/courses/update-topic/${topicId}/`;

          $.ajax({
            type: "POST",
            url: url,
            headers: {
              "X-CSRFToken": "{{ csrf_token }}",
            },
            data: {
              sort_order: newIndex + 1,
              title: topicTitle,
              summary: topicSummary,
            },
            success: function (data) {
              console.log("Topic sort order updated");
            },
            error: function (xhr, status, error) {
              var errorMessage = JSON.parse(xhr.responseText).error_message;
              console.log(errorMessage);
            },
          });
        },
      }
    );

    // Function to update media
    function updateTopic(topicId, newData) {
      $.ajax({
        type: "POST",
        url: `/courses/update-topic/${topicId}/`, // URL to the update_media view
        data: newData,
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
        },
        success: function (response) {
          alert("Topic updated successfully!");
          fetchTopicsList(); // Refresh the media list after successful update
        },
        error: function (xhr, status, error) {
          alert("An error occurred while updating topic.");
        },
      });
    }

    // Event listener for updating media
    $(document).on("click", ".update-topic-btn", function () {
      const topicId = $(this).attr("data-topic-id");
      const newData = {
        title: $(`#title-${topicId}`).val(),
        summary: $(`#summary-${topicId}`).val(),
        sort_order: $(`#sort_order-${topicId}`).val(),
      };
      updateTopic(topicId, newData);
    });

    // Fetch the media list when the page loads
    fetchTopicsList();



    var activeTopicId = null;


    $(".create-lesson-button").click(
      function (e) {
        activeTopicId = $(this).attr("data-topic-id");
        console.log(activeTopicId);
      }
    );

  });
</script>

courses/templates/courses/course_list.html
{% extends "dashboard/base.html" %} {% load static %} {% load my_extras %}
<!--do not remove this commenty-->
{% block content %}
<style>
  .image-grid {
    display: flex;
    flex-wrap: wrap;
    margin: -15px;
  }

  .image-grid-item {
    flex: 0 0 200px;
    position: relative;
    overflow: hidden;
    background-color: rgb(218, 218, 218);
    height: 171.42px;
    cursor: pointer;
    min-width: 300px;
    width: 100%;
  }

  .image-grid-item::before {
    content: "";
    display: block;
    padding-bottom: 100%;
  }

  .image-background {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-size: cover;
    background-position: center;
  }
</style>
<div>
  {% with url_name=request.resolver_match.url_name %}
  <!--Page Title-->
  <div class="container-fluid title-content">
    <div class="py-3">
      <div class="container mt-4">
        <h3 class="fw-normal mb-3" style="letter-spacing: 1px">My Courses</h3>
        <div class="d-flex gap-4 border-bottom mt-3">
          <a
            href="{% url 'courses:list_courses_published' %}"
            class="flex-1 px-4 py-2 {% if url_name == 'list_courses_published' %} text-primary border-bottom border-2"
            style="border-color: #0071dc !important;
                        {% endif %}"
          >
            Publish ({{publish_count}})
          </a>
          <a
            href="{% url 'courses:list_courses_pending' %}"
            class="flex-1 px-4 py-2 {% if url_name == 'list_courses_pending' %}text-primary border-bottom border-2"
            style="border-color: #0071dc !important;
                        {% endif %}"
          >
            Pending ({{pending_count}})
          </a>
          <a
            href="{% url 'courses:list_courses_draft' %}"
            class="flex-1 px-4 py-2 {% if url_name == 'list_courses_draft' %}text-primary border-bottom border-2"
            style="border-color: #0071dc !important;
                        {% endif %}"
          >
            Draft ({{draft_count}})
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endwith %}

  <!-- Page Content -->
  <div class="container my-3">
    {% for course in courses %}
    <div class="card mb-4" style="max-width: 950px">
      <div class="card-body">
        <div class="d-flex flex-column flex-md-row align-items-center">
          <a href="{% url 'courses:course_details' course.pk course.slug %}">
            <div class="image-grid-item rounded">
              <div
                class="image-background"
                style="background-image: url('{% if course.thumbnail %}{{course.thumbnail.file.url}}{% else %}{% static 'images/thumbnail-placeholder.svg' %}{% endif %}')"
              ></div>
            </div>
          </a>
          <div
            class="px-md-3 py-lg-0 py-3 d-flex align-content-center flex-wrap"
            style="width: 100%"
          >
            <div style="width: 100%; height: 130px">
              <div class="d-flex flex-column">
                <span class="greet-text">
                  <i
                    class="fal fa-star fa-sm"
                    style="color: #ffa600; font-size: 14px"
                  ></i>
                  <i
                    class="fal fa-star fa-sm"
                    style="color: #ffa600; font-size: 14px"
                  ></i>
                  <i
                    class="fal fa-star fa-sm"
                    style="color: #ffa600; font-size: 14px"
                  ></i>
                  <i
                    class="fal fa-star fa-sm"
                    style="color: #ffa600; font-size: 14px"
                  ></i>
                  <i
                    class="fal fa-star fa-sm"
                    style="color: #ffa600; font-size: 14px"
                  ></i>
                  <small class="text-muted" style="font-size: 15px"
                    >(2/5)</small
                  >
                </span>
              </div>
              <div class="my-1">
                <b>{{course.title}}</b>
              </div>
              <small>
                <span class="text-muted">Students:</span> <b>0</b>
              </small>
            </div>
            <div
              class="d-flex align-items-center justify-content-between"
              style="width: 100%"
            >
              <div>
                {% if course.discount_price %}
                <b class="fs-5">₹{{course.discount_price|get_price_whole}}</b
                ><b>.{{course.discount_price|get_price_fraction}}</b>
                <s class="text-muted">₹{{course.price|get_price_whole}}</s
                ><s class="text-muted">.{{course.price|get_price_fraction}}</s>
                {% else %}
                <b class="fs-5">₹{{course.price|get_price_whole}}</b
                ><b>.{{course.price|get_price_fraction}}</b>
                {% endif %}
              </div>
              <div class="flex-1 d-flex align-items-center gap-3">
                <a
                  href="{% url 'courses:update_course' course.pk %}"
                  class="btn btn-light border text-muted"
                >
                  <small>
                    <i class="fal fa-pencil-alt text-primary"></i
                    >&nbsp;&nbsp;Edit
                  </small>
                </a>
                <div class="dropdown">
                  <button
                    class="btn btn-outline-primary border rounded-circle dropdown-toggl"
                    type="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    <i class="fal fa-ellipsis-h"></i>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li>
                      <a class="dropdown-item p-3" href="#">
                        <i class="fal fa-share">&nbsp;&nbsp;</i> Share
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item p-3" href="#">
                        <i class="fal fa-copy">&nbsp;&nbsp;</i> Duplicate
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item p-3" href="#">
                        <i class="fal fa-trash">&nbsp;&nbsp;</i> Delete
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% empty %}
    <div class="card">
      <div class="card-body text-muted">
        <b style="font-weight: 500;">You do not have any courses yet.</b>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}