courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    # Main site
    path("", views.course_list, name="course_list"),
    path("<int:pk>/<str:slug>/", views.course_details, name="course_details"),
    path("enroll-course/<int:course_pk>/", views.enroll_course, name="enroll_course"),
    path("lessons/<int:pk>/", views.lesson_details, name="lesson_details"),
    path(
        "lessons/<int:pk>/mark-complete/",
        views.mark_lesson_complete,
        name="mark_lesson_complete",
    ),
    path("assignments/<int:pk>/", views.assignment_details, name="assignment_details"),
    path("quizzes/<int:pk>/", views.quiz_details, name="quiz_details"),
    # Dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("my-courses/", views.list_courses_published, name="list_courses_published"),
    path(
        "my-courses/pending-courses/",
        views.list_courses_pending,
        name="list_courses_pending",
    ),
    path(
        "my-courses/draft-courses/", views.list_courses_draft, name="list_courses_draft"
    ),
    path("create-course/", views.create_course, name="create_course"),
    path("update-course/<int:pk>/", views.update_course, name="update_course"),
    path("list-topics/<int:course_pk>/", views.list_topics, name="list_topics"),
    path("update-topic/<int:pk>/", views.update_topic, name="update_topic"),
    path("create-topic/<int:course_pk>/", views.create_topic, name="create_topic"),
    path("create-lesson/<int:topic_pk>/", views.create_lesson, name="create_lesson"),
    path("create-quiz/<int:topic_pk>/", views.create_quiz, name="create_quiz"),
    path(
        "create-question/<int:quiz_pk>/", views.create_question, name="create_question"
    ),
    path("create-option/<int:question_pk>/", views.create_option, name="create_option"),
    path(
        "create-assignment/<int:topic_pk>/",
        views.create_assignment,
        name="create_assignment",
    ),
    path("update-lesson/<int:pk>/", views.update_lesson, name="update_lesson"),
    path(
        "update-assignment/<int:pk>/", views.update_assignment, name="update_assignment"
    ),
    path("update-quiz/<int:pk>/", views.update_quiz, name="update_quiz"),
    path("update-question/<int:pk>/", views.update_question, name="update_question"),
    path("update-option/<int:pk>/", views.update_option, name="update_option"),
    path(
        "list-topic-item/<int:topic_pk>/",
        views.list_topic_items,
        name="list_topic_items",
    ),
    path(
        "list-questions/<int:quiz_pk>/",
        views.list_questions,
        name="list_questions",
    ),
    path(
        "list-options/<int:question_pk>/",
        views.list_options,
        name="list_options",
    ),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from allauth.account.views import LoginView, SignupView
from users import views as users_views
from courses import views as courses_views

admin.site.site_header = "Skilled MBA Administration"
admin.site.site_title = "Skilled MBA Administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", users_views.profile, name="account_profile"),
    path("ajax-login/", users_views.AjaxLoginView.as_view(), name="ajax_login"),
    path("ajax-signup/", users_views.AjaxSignupView.as_view(), name="ajax_signup"),
    path(
        "",
        courses_views.index,
        name="index",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="sitePages/contactUs.html"),
        name="contact_us",
    ),
    path("media-library/", include("media_library.urls", namespace="media_library")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("", include("users.urls", namespace="users")),
    path("quizzes/", include("quizzes.urls", namespace="quizzes")),
]

# For checking static files in developement only
urlpatterns += [
    path(
        "dashboard/analytics/",
        TemplateView.as_view(template_name="dashboard/instructor/analytics.html"),
        name="analytics",
    ),
    path(
        "dashboard/announcements/",
        TemplateView.as_view(template_name="dashboard/instructor/announcements.html"),
        name="announcements",
    ),
    path(
        "dashboard/quiz-attempts/",
        TemplateView.as_view(template_name="dashboard/instructor/quizAttempts.html"),
        name="quiz_attempts",
    ),
    path(
        "dashboard/withdrawals/",
        TemplateView.as_view(template_name="dashboard/instructor/withdrawals.html"),
        name="withdrawals",
    ),
    path(
        "course-list/",
        TemplateView.as_view(template_name="sitePages/courseList.html"),
        name="course_list",
    ),
    path(
        "course-assignment/",
        TemplateView.as_view(template_name="courseContents/assignment.html"),
        name="course_assignment",
    ),
    path(
        "course-lesson/",
        TemplateView.as_view(template_name="courseContents/lesson.html"),
        name="course_lesson",
    ),
    path(
        "course-quiz/",
        TemplateView.as_view(template_name="courseContents/quiz.html"),
        name="course_quiz",
    ),
    path(
        "enrolled-courses/",
        TemplateView.as_view(template_name="dashboard/student/enrolled_courses.html"),
        name="enrolled_courses",
    ),
    path(
        "reviews/",
        TemplateView.as_view(template_name="dashboard/student/reviews.html"),
        name="reviews",
    ),
    path(
        "wishlist/",
        TemplateView.as_view(template_name="dashboard/student/wishlist.html"),
        name="wishlist",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path(
        "accounts/become-instructor/", views.become_instructor, name="become_instructor"
    ),
    path(
        "instructor-registration/",
        views.InstructorSignupView.as_view(),
        name="instructor_signup",
    ),
    path(
        "search-instructors/<int:course_pk>/",
        views.search_instructors,
        name="search_instructors",
    ),
]

templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Dashboard{% endblock title %} - Skilled MBA</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous" />

    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/tutor-icons.css' %}" />

    <link rel="stylesheet" id="custom-stylesheet-css" type="text/css" media="all"
        href="{% static 'css/dashboard.css' %}" />

    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"
        integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        {% include 'dashboard/sidebar.html' %}

        <!-- Content Wrapper -->
        <div id="page-content-wrapper">

            {% include 'dashboard/header.html' %}

            {% if messages%}
            {% for message in messages %}
            <div
                class="alert alert-{{ message.tags }} rounded-0 mb-0 d-flex align-items-center justify-content-between">
                <span>
                    {{ message }}
                </span>
                <button type="button" class="close btn btn-outline-{{ message.tags }}" data-dismiss="alert"
                    aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif%}




            {% block content %}
            {% endblock content %}


        </div>
    </div>




    <script>
        $(".menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            $(".overlay").toggleClass("toggled");
        });
    </script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>

templates/dashboard/header.html
<!-- Header -->
<header class="shadow-sm position-sticky top-0" style="z-index: 998;">
    <div class="container d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center gap-3 gap-lg-4">
            <a href="#menu-toggle" class="btn btn-light menu-toggle">
                <i class="fas fa-bars"></i>
            </a>
            <img class="user-photo"
                src="https://www.gravatar.com/avatar/cd935c35ae34731f14609bc53055aec6?s=150&r=g&d=mm" alt="user photo">
            <div class="d-flex flex-column">
                <b class="greet-text"><span style="color: #9b9b9b;" class="d-none d-lg-inline">Howdy, </span>
                    {{user.first_name}} {{user.last_name}}</b>
                {% if user.is_instructor %}
                    <span class="greet-text">
                        <i class="fas fa-star fa-sm" style="color: #ffa600; font-size: 14px;"></i>
                        <i class="fas fa-star fa-sm" style="color: #ffa600; font-size: 14px;"></i>
                        <i class="fas fa-star fa-sm" style="color: #c2c2c2; font-size: 14px;"></i>
                        <i class="fas fa-star fa-sm" style="color: #c2c2c2; font-size: 14px;"></i>
                        <i class="fas fa-star fa-sm" style="color: #c2c2c2; font-size: 14px;"></i> 
                        <small>2 <span class="text-secondary">(1 ratings)</span></small>
                    </span>
                {% endif %}
            </div>
        </div>
        <div class="d-flex align-items-center gap-3 gap-lg-4">
            {% if user.is_instructor %}
            <button id="createCourse" class="btn bg-white border px-lg-4 px-3 py-2" style="color: #0071dc;">
                <i class="far fa-edit"></i>
                <span class="d-none d-lg-inline">&nbsp;&nbsp;&nbsp;Add a new course</span>
            </button>
            {% else %}
            <button id="becomeInstructorJS" class="btn bg-white border px-lg-4 px-3 py-2" style="color: #0071dc;">
                <i class="far fa-edit"></i>
                <span class="d-none d-lg-inline">&nbsp;&nbsp;&nbsp;Become an instructor</span>
            </button>
            {% endif %}
            <button class="btn bg-white border px-3 p-2">
                <i class="fas fa-bars"></i>
            </button>
        </div>
    </div>
</header>

<script>
    // Create Course button
    $("#createCourse").click(function (e) {
        e.preventDefault();

        let url = "{% url 'courses:create_course' %}";

        $.ajax({
            type: "POST",
            url: url,
            dataType: 'json',
            headers: {
                "X-CSRFToken": "{{ csrf_token }}",
            },
            success: function (response) {
                if (response.success) {
                    window.location.href = response.redirect_url;
                } else {
                    alert('Failed to create course.');
                }
            },
            error: function (xhr, status, error) {
                alert("Error: " + xhr.responseJSON.error);
                // Handle the error and update the UI accordingly
            },
        });
    });

    // Become instructor button
    $("#becomeInstructorJS").click(function (e) {
        e.preventDefault();

        let url = "{% url 'users:become_instructor' %}";

        $.ajax({
            type: "POST",
            url: url,
            dataType: 'json',
            headers: {
                "X-CSRFToken": "{{ csrf_token }}",
            },
            success: function (response) {
                if (response.success) {
                    window.location.href = response.redirect_url;
                } else {
                    alert('Failed to create course.');
                }
            },
            error: function (xhr, status, error) {
                console.log(xhr)
                console.log(status)
                console.log(error)
                alert("Error: " + xhr.responseJSON.error);
                // Handle the error and update the UI accordingly
            },
        });
    });
</script>

templates/dashboard/sidebar.html
{% load static %}
<!-- Sidebar Wrapper -->
<div id="sidebar-wrapper" class="shadow-sm">
    <button type="button" class="btn position-absolute menu-toggle"
        style="top: 60px; left: 15px; color: rgb(179, 179, 179);">
        <i class="fal fa-times fs-1"></i>
        <span class="sr-only">Toggle Menu</span>
    </button>
    <div class="py-5 d-flex">
        <img class="brandingLogo m-auto" src="{% static 'images/logo.png' %}" loading="lazy" />
    </div>
    <nav id="sidebar">

        {% with url_name=request.resolver_match.url_name %}
        <ul class="list-group p-3">
            <li class="list-group-item p-0 {% if url_name == 'dashboard' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'courses:dashboard' %}">
                    <i class="text-primary fal fa-layer-group fs-5"></i>Dashboard
                </a>
            </li>
            <li
                class="list-group-item p-0 {% if url_name == 'account_profile' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'account_profile' %}">
                    <i class="text-primary fal fa-user fs-5"></i>
                    My Profile
                </a>
            </li>
            <li class="list-group-item p-0 {% if url_name == 'enrolled_courses' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'enrolled_courses' %}">
                    <i class="text-primary fal fa-book-open fs-5"></i>
                    Enrolled Courses
                </a>
            </li>
            <li class="list-group-item p-0 {% if url_name == 'wishlist' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'wishlist' %}">
                    <i class="text-primary fal fa-heart fs-5"></i>
                    Wishlist
                </a>
            </li>
            <li class="list-group-item p-0 {% if url_name == 'reviews' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'reviews' %}">
                    <i class="text-primary fal fa-star fs-5"></i>
                    Reviews
                </a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="#">
                    <i class="text-primary fal fa-question fs-5"></i>
                    My Quiz Attempts
                </a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="#">
                    <i class="text-primary fal fa-shopping-cart fs-5"></i>
                    Order History
                </a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="#">
                    <i class="text-primary fal fa-comments fs-5"></i>
                    Question &amp; Answer
                </a>
            </li>
            {% if not user.is_instructor %}
            <li class="list-group-item d-flex align-items-center gap-3">
                <i class="fal fa-cog fs-5"></i>
                <a href="#">Settings</a>
            </li>
            <li class="list-group-item d-flex align-items-center gap-3">
                <i class="fal fa-sign-out fs-5"></i>
                <a href="{% url 'account_logout' %}" data-no-instant="">Logout</a>
            </li>
            {% endif %}
        </ul>
        {% if user.is_instructor %}
        <span class="p-3">
            Instructor
        </span>
        <ul class="list-group p-3">
            <li class="list-group-item p-0 {% if url_name in "list_courses_published,list_courses_pending,list_courses_draft" %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'courses:list_courses_published' %}">
                    <i class="text-primary fal fa-tv-alt fs-5"></i>My Courses
                </a>
            </li>
            <li class="list-group-item p-0 {% if url_name == 'announcements' %}active{% endif %}">
                <a class="d-flex align-items-center gap-3 p-3" href="{% url 'announcements' %}"><i
                        class="text-primary fal fa-bullhorn fs-5"></i>Announcements</a>
            </li>
            <li class="list-group-item p-0 {% if url_name == 'withdrawals' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'withdrawals' %}"><i
                        class="text-primary fal fa-wallet fs-5"></i>Withdrawals</a>
            </li>
            <li class="list-group-item p-0 {% if url_name in 'quiz_attempts,quiz_attempt_detail' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'quizzes:quiz_attempts' %}"><i
                        class="text-primary fal fa-question fs-5"></i>Quiz Attempts</a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="#"><i class="text-primary fal fa-copy fs-5"></i>Assignments</a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="#"><i class="text-primary fal fa-copy fs-5"></i>Courses to
                    Teach</a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="#"><i class="text-primary fal fa-users fs-5"></i>My Students</a>
            </li>
            <li class="list-group-item p-0 {% if url_name == 'analytics' %}active{% endif %}">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'analytics' %}"><i
                        class="text-primary fal fa-analytics fs-5"></i>Analytics</a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="#"><i class="text-primary fal fa-cog fs-5"></i>Settings</a>
            </li>
            <li class="list-group-item p-0">
                <a class="p-3 d-flex align-items-center gap-3" href="{% url 'account_logout' %}" data-no-instant=""><i
                        class="text-primary fal fa-sign-out fs-5"></i>Logout</a>
            </li>
        </ul>
        {% endif %}
        {% endwith %}
    </nav>
</div>


<div class="overlay menu-toggle"></div>